"""
app/schemas/generation.py
──────────────────────────
Pydantic models for LLM test-case generation.

``TestCase`` mirrors the structured output the LLM is expected to return.
Pydantic is used to validate that every required field is present before the
output is written to disk — if validation fails, the service retries once.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


# ── Structured LLM output ─────────────────────────────────────────────────────


class TestCaseStep(BaseModel):
    """A single step in a test case procedure."""

    step_number: int
    action: str
    expected_result: str = ""


class TestCase(BaseModel):
    """
    A single QA test case generated by the LLM.

    All fields are required — if the LLM omits one, Pydantic raises a
    ValidationError and the service retries the generation.
    """

    title: str = Field(..., min_length=1)
    objective: str = Field(..., min_length=1)
    preconditions: list[str] = Field(default_factory=list)
    steps: list[str] = Field(..., min_length=1)
    expected_result: str = Field(..., min_length=1)
    priority: str = Field(..., pattern=r"^(High|Medium|Low)$")
    requirement_reference: str = Field(..., min_length=1)


class GeneratedTestCaseOutput(BaseModel):
    """The full JSON payload stored on disk."""

    selection_id: int
    document_version_id: int
    node_ids: list[int]
    test_cases: list[TestCase]
    generated_at: str  # ISO 8601 string
    llm_provider: str
    llm_model: str
    prompt_version: str


# ── Request / Response ────────────────────────────────────────────────────────


class GenerateRequest(BaseModel):
    """Request body for POST /api/v1/generate."""

    selection_id: int = Field(..., description="ID of the selection to generate test cases for")


class GenerationResponse(BaseModel):
    """Response after a successful generation."""

    generation_id: int
    selection_id: int
    document_version_id: int
    node_ids: list[int]
    test_cases: list[TestCase]
    generated_at: datetime
    llm_provider: str
    llm_model: str
    prompt_version: str
    is_stale: bool = False


class TestCaseListResponse(BaseModel):
    """Response for GET /api/v1/testcases/{selection_id}."""

    selection_id: int
    total: int
    is_stale: bool
    stale_reason: str
    generated_at: datetime
    document_version_id: int
    test_cases: list[TestCase]
